-- AlterTable
ALTER TABLE "Betrieb" ADD COLUMN     "farbeLinien" TEXT NOT NULL DEFAULT '#9AA5A0',
ADD COLUMN     "farbeText" TEXT NOT NULL DEFAULT '#1C1C1E',
ADD COLUMN     "farbeTitel" TEXT NOT NULL DEFAULT '#1C1C1E',
ADD COLUMN     "logo" TEXT NOT NULL DEFAULT '';
